### ISSUE TITLE
Creation of instance template with container image

### ISSUE THREAD

**Issue by SamyPesse** [pulumi/pulumi-google-native#227]
GCP supports creating instance template to deploy docker container: https://cloud.google.com/compute/docs/containers/deploying-containers#managedinstancegroupcontainer / https://cloud.google.com/sdk/gcloud/reference/beta/compute/instance-templates/create-with-container

But it doesn't seem possible to do it with Pulumi at the moment (with native or the classic). Am I missing something?

**Comment by mikhailshilkov** [comment]
Thank you for your question! It looks like the example you linked uses the beta API of the `compute` service but, indeed, I don't see any container-related properties in the Discovery Document (the API spec) that Google provides, see [here](https://raw.githubusercontent.com/pulumi/pulumi-google-native/master/discovery/compute_beta.json).

I will ask Google folks to check why.

**Comment by mikhailshilkov** [comment]
@SamyPesse One option to figure out what is going on: if you have a gcloud CLI command that works for you, you could run it with `--log-http` parameter and see the actual HTTP requests that it issues. If you paste those in this issue, it would be super helpful.

**Comment by m-strzelczyk** [comment]
Hello! I work with GCP and I can share some insights here.

Unfortunately, creating instances and templates that run containers is currently limited to Cloud Console and `gcloud` tool only. If you go into Cloud Console, click through the Instance creation page and click "Equivalent REST", you'll see the API request with:


```
"metadata": {
    "items": [
      {
        "key": "gce-container-declaration",
        "value": "spec:\n  containers:\n  - name: instance-1\n    image: ngingx\n    stdin: false\n    tty: false\n  restartPolicy: Always\n# This container declaration format is not public API and may change without notice. Please\n# use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine."
      }
    ]
  },
```

Most important is the comment: 
> This container declaration format is not public API and may change without notice. Please use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine.

As you can see, the way we create instances hosting containers is not fully finalized yet and the way it's done is subject to change. Obviously, with the REST preview, you can reverse engineer how it's done right now, but it's not really recommended.

Let me know if you have any further questions.

**Comment by cobraz** [comment]
How about we create an experimental Pulumi Package to handle this? We can release this under Pulumiverse, and I would love to contribute on it.

**Comment by nonylene** [comment]
It's like https://registry.terraform.io/modules/terraform-google-modules/container-vm/google/latest on Terraform

**Comment by nafg** [comment]
If it's just a metadata key `gce-container-declaration` wouldn't it work to just do that explicitly?

**Comment by nafg** [comment]
This is working for me

```yaml
      metadata:
        gce-container-declaration: |
          spec:
            containers:
              - name: gitlab
                image: gitlab/gitlab-ce:17.3.4-ce.0
                env:
                  - name: XXX
                    value: "yyy"
                # volumeMounts:
                #   - name: gitlab-config
                #     readOnly: false
                #     mountPath: /etc/gitlab
            # volumes:
            #   - name: gitlab-config
            #     hostPath:
            #       path: /mnt/gitlab-config/config
```
The volumes syntax seems right but it was failing to start the container, complaining that the host path didn't exist. That could be fixed with cloud init metadata:

```yaml
        user-data: |
          #cloud-config
          runcmd:
            - mkdir -p ...
```
